### ISSUE TITLE
Monitoring of shared variables

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#186]
I have a really simple example (trying to fit `x ** a` to `x ** 2`) where I want to measure my value of `a`, which is stored in a shared variable. I don't want to use `DataStreamMonitoring`, because setting up an entire data stream is kind of overkill. On the other hand, if I feed `a` to `TrainingDataMonitoring` I get the following error:
```
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest plotting.rst[13]>", line 5, in <module>
        extensions=[TrainingDataMonitoring([cost, exponent], after_every_epoch=True),
      File "/home/vanmerb/lisa/blocks/blocks/extensions/monitoring.py", line 88, in __init__
        self._buffer = AggregationBuffer(expressions, use_take_last=True)
      File "/home/vanmerb/lisa/blocks/blocks/monitoring/evaluators.py", line 53, in __init__
        self.inputs = ComputationGraph(self.expressions).inputs
      File "/home/vanmerb/lisa/blocks/blocks/graph.py", line 61, in __init__
        self._get_variables()
      File "/home/vanmerb/lisa/blocks/blocks/graph.py", line 90, in _get_variables
        [dependence])
      File "/home/vanmerb/lisa/Theano/theano/gof/sched.py", line 194, in sort_apply_nodes
        return posort(list_of_nodes(inputs, outputs), *cmps)
      File "/home/vanmerb/lisa/Theano/theano/gof/graph.py", line 1057, in list_of_nodes
        lambda o: [inp.owner for inp in o.inputs
      File "/home/vanmerb/lisa/Theano/theano/gof/graph.py", line 544, in stack_search
        expand_l = expand(l)
      File "/home/vanmerb/lisa/Theano/theano/gof/graph.py", line 1057, in <lambda>
        lambda o: [inp.owner for inp in o.inputs
    AttributeError: 'NoneType' object has no attribute 'inputs'
```
The silly thing is that if I do:
```python
a_copy = a.copy()
```
then I can monitor `a_copy` just fine (I guess because it is no longer a shared variable/has an input).

@rizar What did you have in mind for monitoring shared variables which do not depend on data and don't need a validation set? Or do we simply not support this?

**Comment by bartvm** [comment]
See the relevant code here: http://blocks.readthedocs.org/en/latest/plotting.html

**Comment by rizar** [comment]
We definitely should support this!

From the traceback it looks like the `ComputationGraph` currenly crashes if there is a shared variable in the outputs. I do not think this is a good behavior and intend to fix it.
