### ISSUE TITLE
setup.py does not run without yaml

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#248]
See this failed attempt of installing Blocks:

```
╰─$ python setup.py develop --user 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import blocks.version
  File "/home/rizar/dist/blocks/blocks/__init__.py", line 2, in <module>
    from blocks.config_parser import config  # flake8: noqa
  File "/home/rizar/dist/blocks/blocks/config_parser.py", line 54, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by bartvm** [comment]
Let me know whether that fixed it.

**Comment by arasmus** [comment]
It did!
