### ISSUE TITLE
test_doctest.py fails to run on OSX

### ISSUE THREAD

**Issue by vdumoulin** [bartvm/blocks#286]
I've been unable to run doctests because calling `nosetests tests/test_doctest.py` from the root of the repo raises the following error:

```
$ nosetests tests/test_doctest.py
E
======================================================================
ERROR: test suite for <module 'tests.test_doctest' from '<BLOCKS_DIRECTORY>/blocks/tests/test_doctest.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/util.py", line 467, in try_run
    return func(obj)
  File "<BLOCKS_DIRECTORY>/blocks/tests/test_doctest.py", line 17, in setup
    testobj.globs['absolute_import'] = absolute_import
AttributeError: 'module' object has no attribute 'globs'

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)
```

About my setup:
* OSX 10.10.2
* nosetests 1.3.1, installed through macports
* Python 2.7.9, installed through macports

**Comment by bartvm** [comment]
You need to use `nose2`, see http://blocks.readthedocs.org/en/latest/development/index.html#unit-testing

The reason for this is that `nose2` supports a particular kind of hook that I use to perform some  `__future__` imports in Python 2. Otherwise the doctests (which are written in Python 3) would give a slightly different output (e.g. for the `print` function or unicode strings) and fail.

**Comment by vdumoulin** [comment]
Good to know, thanks!
