### ISSUE TITLE
Can Not Install Blocks at LISA Computer

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#403]
See below 

```
╭─bahdanau@eos16  ~/Dist/blocks  ‹master*› 
╰─$ pip --version
pip 1.3.1 from /opt/lisa/os/lib64/python2.7/site-packages (python 2.7)
╭─bahdanau@eos16  ~/Dist/blocks  ‹master*› 
╰─$ pip install git+git://github.com/bartvm/blocks.git \
>   -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt
Exception:
Traceback (most recent call last):
  File "/opt/lisa/os/lib/python2.7/site-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/opt/lisa/os/lib/python2.7/site-packages/pip/commands/install.py", line 240, in run
    for req in parse_requirements(filename, finder=finder, options=options):
  File "/opt/lisa/os/lib/python2.7/site-packages/pip/req.py", line 1356, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from)
  File "/opt/lisa/os/lib/python2.7/site-packages/pip/req.py", line 118, in from_line
    return cls(req, comes_from, url=url)
  File "/opt/lisa/os/lib/python2.7/site-packages/pip/req.py", line 43, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/opt/lisa/os/lib/python2.7/site-packages/pkg_resources.py", line 2725, in parse
    reqs = list(parse_requirements(s))
  File "/opt/lisa/os/lib/python2.7/site-packages/pkg_resources.py", line 2650, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/opt/lisa/os/lib/python2.7/site-packages/pkg_resources.py", line 2618, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', '--allow-external picklable-itertools', 'at', ' picklable-itertools')
```

**Comment by bartvm** [comment]
Pip 1.3.1? Got to be kidding me.... Please enable Fred's newer configuration (`os_v3`) to get pip 1.5.6 at least :)

**Comment by bartvm** [comment]
BTW, I actually run Anaconda from my home directory, which works quite nicely. Latest versions of all packages, binary installs, MKL, and you don't have to deal with the lab's old packages anymore.

**Comment by rizar** [comment]
Thanks for advice. I updated to os_v3, and this is what I get:

```
╭─bahdanau@eos16  ~/Dist/blocks  ‹master*› 
╰─$ pip install git+git://github.com/bartvm/blocks.git \
  -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt
Downloading/unpacking git+git://github.com/bartvm/blocks.git
  Cloning git://github.com/bartvm/blocks.git to /tmp/pip-dlUOqI-build
  Running setup.py (path:/tmp/pip-dlUOqI-build/setup.py) egg_info for package from git+git://github.com/bartvm/blocks.git
    
  Requirement already satisfied (use --upgrade to upgrade): blocks==0.1a1 from git+git://github.com/bartvm/blocks.git in /u/bahdanau/Dist/blocks
Requirement already satisfied (use --upgrade to upgrade): picklable-itertools from git+https://github.com/dwf/picklable_itertools.git in /part/02/Tmp/lisa/os_v3/lib/python2.7/site-packages (from -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): theano from git+https://github.com/Theano/Theano.git in /u/bahdanau/Dist/theano (from -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt (line 7))
Downloading/unpacking fuel from git+https://github.com/bartvm/fuel (from -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt (line 11))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/pip/req.py", line 1153, in prepare_files
    location = req_to_install.build_location(self.build_dir, not self.is_download)
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/pip/req.py", line 218, in build_location
    _make_build_dir(build_dir)
  File "/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/lib/python2.7/site-packages/pip/req.py", line 1527, in _make_build_dir
    os.makedirs(build_dir)
  File "/u/lisa/local/install_package.fc14_v3/Canopy1.4/appdata/canopy-1.4.0.1938.rh5-x86_64/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/u/lisa/local/export.soft.lisa.master/linux-x86_64-fc14.x86_64_v3/canopy/build'

Storing debug log for failure in /u/bahdanau/.pip/pip.log
```

**Comment by bartvm** [comment]
That's because pip by default tries to build its packages in what it thinks is the virtual environment (Canopy in this case), but you don't have write access. You can fix it by setting a custom build directory for pip somewhere where you do have access e.g. pass `-b ~/.pip_build`.

This is a problem that isn't Blocks-specific by the way, it's just because of the way the LISA Python environment is setup AFAIK.

**Comment by dwf** [comment]
@bartvm Home directory is fast enough for serving binaries? Is there
something special needed to get an academic license for the MKL extensions?

**Comment by bartvm** [comment]
University of Montreal is in their list of approved institutions, so you can get one simply by filling out the form and get one for free (button on the top right): https://store.continuum.io/cshop/academicanaconda

I've had no problems with speed, but I guess that if it does turn out to be problem, maybe it's possible to write a script that automatically copies the files to /Tmp, or uses `conda create -p` to create an environment on /Tmp?

**Comment by dwf** [comment]
Ooh, I just noticed `conda create --copy`. :)

**Comment by bartvm** [comment]
So maybe something like this could work?

```bash
if [ ! -d "/Tmp/$USER/anaconda" ]; then
    echo "Installing Python to local computer"
    conda create --copy --clone my_py_env -p /Tmp/$USER/anaconda -n my_local_py_env
else
    echo "Updating local Anaconda installation"
    conda list -n my_py_env --export > .my_py_env.txt
    conda update -n my_local_py_env --file .my_py_env.txt
fi
```

**Comment by dwf** [comment]
My my, the future is wonderful.
