### ISSUE TITLE
Errors in running the example of MNIST. What should I do

### ISSUE THREAD

**Issue by haanvid** [bartvm/blocks#626]
Hi I just installed Theano and Blocks.
And ran the MNIST examle given in the sight.
But I got this error and don't know what to do with it
>
 _>>> from fuel.datasets import MNIST
 _>>> mnist = MNIST("train")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 36, in __init__
    super(MNIST, self).__init__(self.data_path, which_set, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 131, in __init__
    if which_set not in self.available_splits:
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 243, in available_splits
    return tuple(self.split_dict.keys())
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 224, in split_dict
    self._out_of_memory_open()
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 289, in _out_of_memory_open
    handle = h5py.File(name=self.path, mode="r", driver=self.driver)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2453)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2410)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip_build_root/h5py/h5py/h5f.c:1787)
IOError: Unable to open file (Unable to open file: name = '/home/user/datasets/mnist.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
>

I downloaded these datasets from the site mentioned in the Blocks site.
t10k-images-idx3-ubyte
t10k-labels-idx1-ubyte
train-images-idx3-ubyte
train-labels-idx1-ubyte

And extracted the files from the compressed ones and put it in the home/user/datasets/mnist 
(modified the 'user' to my user name)

And also added path to ~/.fuelrc
first I added home/user/datasets  as it is told on the Blocks site
and then seeing that it doesn't work I also included home/user/datasets/mnist to the path.

And it still doesn't work.
What should I do to fix this problem?

**Comment by vdumoulin** [comment]
This is more of a Fuel issue.

There are binaries in Fuel that manage data downloading (`fuel-download`) and data conversion (`fuel-convert`). To download and convert the MNIST dataset, run

``` bash
cd $FUEL_DATA_PATH
fuel-download mnist
fuel-convert mnist
fuel-download --clear mnist
cd -
```

**Comment by haanvid** [comment]
@vdumoulin 

Now I got 'mnist.hdf5'
but I have new bug...

>
_>>>from fuel.datasets import MNIST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named fuel.datasets
>

**Comment by vdumoulin** [comment]
When was your last pull on Fuel?

**Comment by haanvid** [comment]
@vdumoulin  I'm new to GitHub, it's my first time using it(started to using it 2 days ago). I just seen the tutorial on GitHub and if you are referring 'pull' to making a commit or modification to the code, I haven't. But I look forward to making it. Now I'm not so good on coding and using this stuff

**Comment by vdumoulin** [comment]
From your issue in Blocks I get that you did not explicitly install Fuel, correct?

I was assuming that you cloned the Fuel repo, but my question doesn't really apply in your case. You should be able to upgrade to the latest Fuel version using the command I gave you the Blocks issue.

By the way, in the future, there are mailing lists for [Fuel](https://groups.google.com/d/forum/fuel-users) and [Blocks](https://groups.google.com/d/forum/blocks-users) that you can use to ask questions.

**Comment by haanvid** [comment]
@vdumoulin  Thanks a lot!
